### ISSUE TITLE
[Bug]: Crash when placing Sign on a wooden hopper 

### ISSUE THREAD

**Issue by randomleech** [cech12/WoodenHopper#24]
### Minecraft Version

1.20.4

### Mod Loader

NeoForge

### Mod Loader Version

20.4.223

### Mod Version

2.1.0.0

### Modpack or other Mod

I highly doubt it's any mod conflict. I use mods like extra dungeons, enchants, auto crop placing, fast leaves decay after tree chopping, etc. This is the only mod which does anything with hoppers, or even storage items (altho extra dungeons could have modified chest loot...)
![signoverhopper](https://github.com/cech12/WoodenHopper/assets/167005722/c1c875da-8875-4ede-94f6-fb4b5bb05c8f)
.

### Describe the Issue

Hopper was placed under flowing water (4 sources, from 4 corners of a 5x5 square, were leading into hopper, and hopper was going into chest (checked, was working). then I crouched, and tried to put a sign on hopper, and got this:

The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "net.neoforged.neoforge.items.IItemHandler.getSlots()" because "handler" is null
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.lambda$pullItems$3(NeoForgeWoodenHopperBlockEntity.java:276) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.pullItems(NeoForgeWoodenHopperBlockEntity.java:272) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.lambda$tick$0(NeoForgeWoodenHopperBlockEntity.java:133) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.updateHopper(NeoForgeWoodenHopperBlockEntity.java:147) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.tick(NeoForgeWoodenHopperBlockEntity.java:133) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:691) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:771) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:545) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:409) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin from mod leavesbegone,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:969) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:855) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:106) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:700) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.lambda$pullItems$3(NeoForgeWoodenHopperBlockEntity.java:276) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.pullItems(NeoForgeWoodenHopperBlockEntity.java:272) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.lambda$tick$0(NeoForgeWoodenHopperBlockEntity.java:133) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.updateHopper(NeoForgeWoodenHopperBlockEntity.java:147) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity.tick(NeoForgeWoodenHopperBlockEntity.java:133) ~[woodenhopper-neoforge-1.20.4-2.1.0.0.jar%23284!/:1.20.4-2.1.0.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:691) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:771) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:545) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: woodenhopper:wooden_hopper // de.cech12.woodenhopper.blockentity.NeoForgeWoodenHopperBlockEntity
	Block: Block{woodenhopper:wooden_hopper}[enabled=true,facing=north]
	Block location: World: (1376,62,2517), Section: (at 0,14,5 in 86,3,157; chunk contains blocks 1376,-64,2512 to 1391,319,2527), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
	Block: Block{woodenhopper:wooden_hopper}[enabled=true,facing=north]
	Block location: World: (1376,62,2517), Section: (at 0,14,5 in 86,3,157; chunk contains blocks 1376,-64,2512 to 1391,319,2527), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:691) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:771) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading}
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:545) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:409) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin from mod leavesbegone,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:969) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:855) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:106) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:700) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[client-1.20.4-20231207.154220-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no performance mods

**Comment by cech12** [comment]
Thanks for your report! That is a really bad bug^^
I fixed that in the upcoming version 1.20.4-2.1.0.1
